[versions]
agp = "8.7.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"
appcompat = "1.7.0"
localbroadcastmanagerVersion = "1.1.0"
material = "1.12.0"
constraintlayout = "2.2.1"
navigationFragment = "2.8.8"
navigationUi = "2.8.8"
annotations = "23.0.0"
activity = "1.9.0"
gson = "2.12.1"
yasee = "0.9.227"
wl = "1.0.2"
hlw = "1.0.3"
yc = "0.9.14"
masschip = "0.9.5"
usfa = "3.9.0"
ggld = "2.1.5"
mz = "0.9.0"
ky = "0.9.0"
#tesseract-android = "5.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanagerVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
yasee = { module = "com.yasee.yasee:yasee", version.ref = "yasee" }
wl = { module = "com.yasee.wl:wl", version.ref = "wl" }
hlw = { module = "com.yasee.hlw:hlw", version.ref = "hlw" }
yc = { module = "com.yasee.yc:yc", version.ref = "yc" }
mz = { module = "com.yasee.mz:mz", version.ref = "mz" }
ky = { module = "com.yasee.ky:ky", version.ref = "ky" }
masschip = { module = "com.yasee.masschip:masschip", version.ref = "masschip" }
usfa = { module = "com.github.mik3y:usb-serial-for-android", version.ref = "usfa" }
ggld = { module = "com.licheedev:android-serialport", version.ref = "ggld" }
#tesseract-android = { group = "com.googlecode.tesseract.android", name = "tesseract-android", version.ref = "tesseract-android" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
tools-grease = { id = "io.deepmedia.tools.grease", version = "0.3.3" }

